/* Auto generated file by build envsetup shell.
 !!!!!!!! Do not edit this file. !!!!!!!!
 Created time : Thu Jul 17 15:50:40 KST 2014
TARGET_BUILD_BOARDVER : tp25
*/

#define CONFIG_BOARD_VER CONFIG_TP25

